version: '3'
services:
  sftp:
    container_name: sftp-embers
    image: "emberstack/sftp"
    ports:
      - "6022:22"
    volumes:
      - ./config/sftp.json:/app/config/sftp.json:ro
      - ./volume:/app