version: '3.8'

services:  

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dbname
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5400:5432"
